

deploy:
  provider: testfairy
  api-key: "TESTFAIRY API KEY"
  app-file: bin/MainActivity_release.apk
  symbols-file: bin/proguard_mapping.txt
  keystore-file: /root/app.keystore
  storepass: swordfish
  alias: android
  testers-groups: qa-stuff,friends
  auto-update: true
  screenshot-interval: 2
  video: true
  video-quality: high
  icon-watermark: true
  data-only-wifi: true
  metrics: cpu,memory,network,phone-signal,logcat,gps,battery
  advanced-options: shake,anonymous
